#! /bin/bash
set -x
home="/var/lib/envsensor"
# Creando usuario y grupo
addgroup --system envsensor
adduser --system --home $home --no-create-home --ingroup envsensor envsensor
# Creando archivos y directorios
mkdir -p $home/log
chown envsensor:www-data $home/log
chmod 770 $home/log
cp modServer.py modServers.sh index.py graph.py eventos.py dbconn.py sample.py sensores.json crontab apache2.conf $home
chmod 400 $home/*.py
chown envsensor:envsensor $home/*.py
chown envsensor:envsensor $home/*.sh
chmod 100 $home/{modServer.py,modServers.sh}
chown root:root $home/{modServer.py,modServers.sh}
chown www-data:envsensor $home/{dbconn.py,graph.py}
chmod 500 $home/{sample.py,index.py}
chown www-data:envsensor $home/{sample.py,index.py}
# Crontab config
crontab -u envsensor $home/crontab
# Apache2 config
ln -s /var/lib/envsensor/apache2.conf /etc/apache2/conf-enabled/envsensor.conf
# Reiniciando servicios
systemctl reload apache2

