#! /bin/bash
set -x
home="/var/lib/envsensor"
# Creando usuario y grupo
addgroup --system envsensor
adduser --system --home $home --no-create-home --ingroup envsensor envsensor
# Creando archivos y directorios
mkdir -p $home/log
chown envsensor:www-data $home/log
chmod 770 $home/log
cp modServers.sh index.py graph.py eventos.py dbconn.py sample.py sensores.json crontab apache2.conf $home
chmod 555 $home/modServers.sh
chmod 400 $home/*.py
chown envsensor:envsensor $home/*.py
chmod 400 $home/dbconn.py
chown www-data:envsensor $home/dbconn.py
chmod 500 $home/{sample.py,index.py}
chown www-data:envsensor $home/{sample.py,index.py}
# Crontab config
crontab -u envsensor $home/crontab
# Apache2 config
ln -s /var/lib/envsensor/apache2.conf /etc/apache2/conf-enabled/envsensor.conf
# Reiniciando servicios
systemctl reload apache2

